/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */
import * as React from 'react';
import { IVwoData } from './vwo.data';
import { IVwoProps } from './vwo.props.autogenerated';

export interface IVwoViewProps extends IVwoProps<IVwoData> {}

/**
 *
 * Vwo component
 * @extends {React.PureComponent<IVwoProps<IVwoData>>}
 */
class Vwo extends React.PureComponent<IVwoProps<IVwoData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default Vwo;
