/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Vwo from '../vwo';
import { IVwoData } from '../vwo.data';
import { IVwoConfig, IVwoProps } from '../vwo.props.autogenerated';

const mockData: IVwoData = {
    actionResponse: {
        text: 'Sample Response Data'
    },
    accountId: 437674,
    settingsTolerance: 2000,
    libraryTolerance: 2500,
    useExistingJquery: false,
    isSPA: 1
};

const mockConfig: IVwoConfig = {
    accountId: 437674,
    settingsTolerance: 2000,
    libraryTolerance: 2500,
    useExistingJquery: false,
    isSPA: 1
};

const mockActions = {};

describe('Vwo', () => {
    let moduleProps: IVwoProps<IVwoData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IVwoProps<IVwoData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<Vwo {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
